=== Aleyasen/xcurator-data/mapping/mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.cs.toronto.edu/xml2rdf/mapping/v1" 
        xmlns:mapping="http://www.cs.toronto.edu/xml2rdf/mapping/v1" 
        elementFormDefault="qualified">
  
    <element name="mapping" type="mapping:mapping"/>
    
    <complexType name="mapping">
        <sequence>
            <element name="entity" type="mapping:entity" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="entity">
        <sequence>
            <element name="id" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="property" type="mapping:property" minOccurs="1" maxOccurs="unbounded"/>
            <element name="relation" type="mapping:relation" maxOccurs="unbounded" minOccurs="0"/>
            <element name="lookupkey" type="mapping:lookupkey" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="type" type="anyURI" use="required"/>
        <attribute name="path" type="string" use="required"/>
    </complexType>

    <complexType name="lookupkey">
        <sequence>
            <element name="property" type="string" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" type="anyURI" use="required"/>
    </complexType>

    <complexType name="foreignlookupkey">
        <sequence>
            <element name="target-property" type="mapping:property" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>

    <complexType name="relation">
        <sequence>
            <element name="lookupkey" type="mapping:foreignlookupkey" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
        <attribute name="targetentity" type="anyURI" use="required"/>
        <attribute name="path" type="string" use="required"/>
    </complexType>
    
    <complexType name="property">
        <attribute name="name" type="anyURI" use="required"/>
        <attribute name="type" type="string" use="optional"/>
        <attribute name="path" type="string" use="required"/>
    </complexType>
    
</schema>

=== Aleyasen/xcurator-data/mapping/minimalmapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    xmlns="http://www.cs.toronto.edu/xml2rdf/mapping/v1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.cs.toronto.edu/xml2rdf/mapping/v1 mapping.xsd ">
  
    <entity type="http://www.isbn.org/Book" path="/">

        <!-- 
         Implicit elements for provenance:
           1. Source URI
           2. Date of retrieval
           3. Source checksum
           4. Version
        -->
        <id>http://www.isbn.org/Book#${title}</id>
  
        <property name="title" path="/" type="string"/>

        <relation name="" path="" targetentity="http://www.example.org/#Publisher">
            <lookupkey name="">
                <target-property name="name" path="/publisher/text()"/>
            </lookupkey>
        </relation>

        <relation name="" path="" targetentity="http://xmlns.com/foaf/0.1/Person">
            <lookupkey name="">
                <target-property name="name" path="/publisher/text()"/>
            </lookupkey>
        </relation>

        <lookupkey name="http://tempuri.org">
            <property>property</property>
        </lookupkey>

    </entity>

</mapping>

=== Aleyasen/xcurator-data/clinicaltrials/mapping/linkedct-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.cs.toronto.edu/xml2rdf/mapping/v1"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.cs.toronto.edu/xml2rdf/mapping/v1 ../mapping/mapping.xsd ">

    <entity path="/clinical_study/location/facility" type="http://www.linkedct.org/0.1#Facility">
        <id>http://www.linkedct.org/0.1#${name/text()}</id>
        <property name="http://www.linkedct.org/0.1#name" path="name/text()" />
        <property name="http://www.linkedct.org/0.1#city" path="address/city/text()" />
        <property name="http://www.linkedct.org/0.1#state" path="address/state/text()" />
        <property name="http://www.linkedct.org/0.1#zip" path="address/zip/text()" />
        <property name="http://www.linkedct.org/0.1#country" path="address/country/text()" />
    
        <lookupkey name="http://www.linkedct.org/0.1#FacilityLookupById">
            <property>id</property>
        </lookupkey>
    </entity>

    <entity path="/clinical_study" type="http://www.linkedct.org/0.1#ClinicalStudy">

        <id>http://www.linkedct.org/0.1#${id_info/nct_id/text()}</id>
    
        <!-- Other identifiers -->
        <property name="http://www.linkedct.org/0.1#orgStudyId" path="id_info/org_study_id/text()" />
        <property name="http://www.linkedct.org/0.1#secondaryId" path="id_info/secondary_id/text()" />

        <!-- Date information -->    
        <property name="http://www.linkedct.org/0.1#verificationDate" path="verification_date/text()" />

        <relation name="http://www.linkedct.org/0.1#location" path="location/facility" 
              targetEntity="http://www.linkedct.org/0.1#Facility">
        
            <lookupkey name="">
                <target-property name="http://www.linkedct.org/0.1#name" path="name/text()" />
            </lookupkey>
      
        </relation>

        <lookupkey name="http://www.linkedct.org/0.1#ClinicalStudyLookupById">
            <property>id</property>
        </lookupkey>

    </entity>

</mapping>
